# Generated by Django 5.1.2 on 2024-11-27 07:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bioclass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nameclass', models.CharField(help_text='Enter a class(e.g. chronobiotics, radioprotectors)', max_length=128)),
            ],
            options={
                'db_table': 'class',
            },
        ),
        migrations.CreateModel(
            name='Mechanism',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mechanismname', models.CharField(help_text='Enter a mechanism(e.g. relax, energy, tea , coffe)', max_length=128)),
            ],
            options={
                'db_table': 'mechanism',
            },
        ),
        migrations.CreateModel(
            name='Targets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('targetsname', models.CharField(help_text='Enter a target(Txxxxx)', max_length=150)),
                ('targeturl', models.URLField(help_text='Enter a link about this target')),
            ],
            options={
                'db_table': 'target',
            },
        ),
        migrations.CreateModel(
            name='Chronobiotic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gname', models.CharField(max_length=128, unique=True)),
                ('smiles', models.CharField(max_length=256, unique=True)),
                ('linkname', models.SlugField(max_length=256, null=True)),
                ('molecula', models.CharField(max_length=256, unique=True)),
                ('iupacname', models.CharField(max_length=256, unique=True)),
                ('updphoto', models.ImageField(upload_to='media/')),
                ('description', models.TextField(blank=True, help_text='Enter a  description of the biotic', max_length=1000)),
                ('fdastatus', models.CharField(blank=True, max_length=64, null=True)),
                ('article', models.URLField(blank=True, null=True)),
                ('linkslists', models.URLField(blank=True, null=True)),
                ('pubchem', models.URLField(blank=True, null=True)),
                ('chemspider', models.URLField(blank=True, null=True)),
                ('drugbank', models.URLField(blank=True, null=True)),
                ('chebi', models.URLField(blank=True, null=True)),
                ('uniprot', models.URLField(blank=True, null=True)),
                ('kegg', models.URLField(blank=True, null=True)),
                ('selleckchem', models.URLField(blank=True, null=True)),
                ('classf', models.ManyToManyField(help_text='Select a class for this molecula', to='main.bioclass')),
                ('mechanisms', models.ManyToManyField(help_text='Select a synonyms of this ', to='main.mechanism')),
                ('target', models.ManyToManyField(help_text='Select a targets of this ', to='main.targets')),
            ],
            options={
                'db_table': 'chronobiotic',
            },
        ),
        migrations.CreateModel(
            name='Synonyms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('synonymsmname', models.CharField(help_text='Enter a synonyms', max_length=128)),
                ('originalbiotic', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='main.chronobiotic')),
            ],
            options={
                'db_table': 'synonyms',
            },
        ),
    ]
