# Generated by Django 5.1.2 on 2024-11-27 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='targets',
            name='targetsfullname',
            field=models.CharField(blank=True, help_text='Enter a target(Txxxxx)', max_length=150),
        ),
    ]
