# Generated by Django 5.1.2 on 2024-12-06 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_targets_targetsfullname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='targets',
            name='targetsfullname',
            field=models.CharField(blank=True, help_text='Enter a fullname', max_length=150),
        ),
    ]
