# Generated by Django 5.1.2 on 2025-03-26 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_targets_targetsfullname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chronobiotic',
            name='description',
            field=models.TextField(blank=True, help_text='Enter a  description of the biotic', max_length=5000),
        ),
    ]
