# Generated by Django 5.1.2 on 2025-05-14 11:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_chronobiotic_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Effect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Effectname', models.CharField(help_text='Enter your effect', max_length=150)),
                ('articleurl', models.URLField(help_text='Enter a link about this article', max_length=350)),
            ],
            options={
                'db_table': 'effect',
            },
        ),
        migrations.AlterField(
            model_name='chronobiotic',
            name='mechanisms',
            field=models.ManyToManyField(help_text='Select a mechanism of this ', to='main.mechanism'),
        ),
        migrations.AlterField(
            model_name='synonyms',
            name='originalbiotic',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='synonyms', to='main.chronobiotic'),
        ),
        migrations.AddField(
            model_name='chronobiotic',
            name='effect',
            field=models.ManyToManyField(help_text='Select a effects of this ', to='main.effect'),
        ),
    ]
