# Generated by Django 5.1.2 on 2025-05-14 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_effect_alter_chronobiotic_mechanisms_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chronobiotic',
            name='effect',
            field=models.ManyToManyField(blank=True, help_text='Select a effects of this ', to='main.effect'),
        ),
    ]
