# Generated by Django 5.1.2 on 2025-05-14 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_chronobiotic_effect'),
    ]

    operations = [
        migrations.CreateModel(
            name='Articles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('articlename', models.CharField(help_text='articlename', max_length=500)),
                ('articleurl', models.URLField(help_text='Enter a link about this target', max_length=250)),
            ],
            options={
                'db_table': 'article',
            },
        ),
        migrations.RemoveField(
            model_name='chronobiotic',
            name='article',
        ),
        migrations.RemoveField(
            model_name='effect',
            name='articleurl',
        ),
        migrations.AddField(
            model_name='chronobiotic',
            name='articles',
            field=models.ManyToManyField(help_text='Select a targets of this ', to='main.articles'),
        ),
    ]
