
# Generated by Django 5.1.2 on 2025-05-14 18:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_articles_remove_chronobiotic_article_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chronobiotic',
            name='articles',
        ),
        migrations.RemoveField(
            model_name='chronobiotic',
            name='effect',
        ),
        migrations.AddField(
            model_name='chronobiotic',
            name='article',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='chronobiotic',
            name='mechanisms',
            field=models.ManyToManyField(help_text='Select a synonyms of this ', to='main.mechanism'),
        ),
        migrations.AlterField(
            model_name='synonyms',
            name='originalbiotic',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='main.chronobiotic'),
        ),
        migrations.DeleteModel(
            name='Articles',
        ),
        migrations.DeleteModel(
            name='Effect',
        ),
    ]
