# Generated by Django 5.1.2 on 2025-05-15 10:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_remove_chronobiotic_articles_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Articles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('articlename', models.CharField(help_text='articlename', max_length=500)),
                ('articleurl', models.URLField(help_text='Enter a link about this target', max_length=250)),
            ],
            options={
                'db_table': 'article',
            },
        ),
        migrations.CreateModel(
            name='Effect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Effectname', models.CharField(help_text='Enter your effect', max_length=150)),
            ],
            options={
                'db_table': 'effect',
            },
        ),
        migrations.RemoveField(
            model_name='chronobiotic',
            name='article',
        ),
        migrations.AlterField(
            model_name='chronobiotic',
            name='mechanisms',
            field=models.ManyToManyField(help_text='Select a mechanism of this ', to='main.mechanism'),
        ),
        migrations.AlterField(
            model_name='synonyms',
            name='originalbiotic',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='synonyms', to='main.chronobiotic'),
        ),
        migrations.AddField(
            model_name='chronobiotic',
            name='articles',
            field=models.ManyToManyField(help_text='Select a targets of this ', to='main.articles'),
        ),
        migrations.AddField(
            model_name='chronobiotic',
            name='effect',
            field=models.ManyToManyField(blank=True, help_text='Select a effects of this ', to='main.effect'),
        ),
    ]
